// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TasksBoard.Models;

namespace TasksBoard.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20190325051732_TasksTableAdd")]
    partial class TasksTableAdd
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TasksBoard.Models.TaskModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateAdd");

                    b.Property<DateTime>("DateFinish");

                    b.Property<string>("EmployeesList");

                    b.Property<int>("ParentTaskId");

                    b.Property<decimal>("PlanHours");

                    b.Property<int>("State");

                    b.Property<string>("TaskContent")
                        .IsRequired()
                        .HasMaxLength(6000);

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasMaxLength(600);

                    b.Property<decimal>("TotalHours");

                    b.HasKey("Id");

                    b.ToTable("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
